config/routes.rb
CountryData::Application.routes.draw do
  match "world/index" => "world#index", :as => 'world', :via => :get

  match "world/by_population" => "world#by_population", :as => 'by_population', :via => :get

  match "world/by_age" => "world#by_age", :as => 'by_age', :via => :get

  match "world/by_required_service" => 'world#by_required_service', :as => 'by_required_service', :via => :get
  
  match "world/results" => "world#search_results", :as => 'results', :via => :post

  resources :countries

end

app/models/country.rb
class Country < ActiveRecord::Base
  ALLOWED_COUNTRIES = ["Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
        "Anguilla", "Antarctica", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria",
        "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
        "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil",
        "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
        "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
        "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo",
        "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
        "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)",
        "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
        "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar",
        "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
        "Guinea-Bissau", "Guyana", "Haiti", "Heard and McDonald Islands", "Holy See (Vatican City State)",
        "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of", "Iraq",
        "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
        "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan",
        "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic Of",
        "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
        "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of",
        "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
        "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
        "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau",
        "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation",
        "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia",
        "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
        "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
        "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname",
        "Svalbard and Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
        "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste",
        "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
        "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
        "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
        "Viet Nam", "Virgin Islands, British", "Virgin Islands, U.S.", "Wallis and Futuna", "Western Sahara",
        "Yemen", "Zambia", "Zimbabwe"
        ]
  
  attr_accessible :gross_domestic_product, :life_expectancy, :mandatory_military_service, :median_age, :name, :population
  
  # validate presence and numericality of the following fields
  validates_presence_of :name, :population, :median_age, :life_expectancy, :gross_domestic_product
  validates_numericality_of :population, :median_age, :life_expectancy, :gross_domestic_product
  
  # validate unique name and that it is within our allowed names
  validates_uniqueness_of :name
  validates_inclusion_of :name, :in => ALLOWED_COUNTRIES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/world_controller.rb
class WorldController < ApplicationController
  def index
    @countries = Country.order("name DESC")
  end

  def by_population
    @countries = Country.order("population DESC")
  end

  def by_age
    @countries = Country.where("median_age > 30").order("median_age ASC")
  end

  def by_required_service
    @countries = Country.where(:mandatory_military_service => true).order('life_expectancy DESC')
  end
  
  # There is a associated view for this action
  def search
  end
 
  def search_results
    @keyword = params[:keyword]
    @filter = params[:my_option]
    
    if @filter == "1"
      @countries = Country.where("Name LIKE ?", "%#{@keyword}%")
    elsif @filter == "2"
      @countries = Country.where("Name LIKE ? AND mandatory_military_service == ?", "%#{@keyword}%", true)
    elsif @filter == "3"
      @countries = Country.where("Name LIKE ? AND mandatory_military_service == ?", "%#{@keyword}%", false)
    else
      @countries = ""
    end
    
    
    
    if @countries.empty?
      flash[:notice] = "No countries were found. with keyword #{@keyword}"
      session[:keyword] = @keyword
      redirect_to :action => 'index'
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/world_helper.rb
module WorldHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.select :name, Country::ALLOWED_COUNTRIES %>
  </div>
  <div class="field">
    <%= f.label :population %><br />
    <%= f.text_field :population %>
  </div>
  <div class="field">
    <%= f.label :median_age %><br />
    <%= f.text_field :median_age %>
  </div>
  <div class="field">
    <%= f.label :life_expectancy %><br />
    <%= f.text_field :life_expectancy %>
  </div>
  <div class="field">
    <%= f.label :gross_domestic_product %><br />
    <%= f.text_field :gross_domestic_product %>
  </div>
  <div class="field">
    <%= f.label :mandatory_military_service %><br />
    <%= f.check_box :mandatory_military_service %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Population</th>
    <th>Median age</th>
    <th>Life expectancy</th>
    <th>Gross domestic product</th>
    <th>Mandatory military service</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @countries.each do |country| %>
  <tr>
    <td><%= country.name %></td>
    <td><%= country.population %></td>
    <td><%= country.median_age %></td>
    <td><%= country.life_expectancy %></td>
    <td><%= number_to_currency(country.gross_domestic_product) %></td>
    <td><%= country.mandatory_military_service %></td>
    <td><%= link_to 'Show', country %></td>
    <td><%= link_to 'Edit', edit_country_path(country) %></td>
    <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @country.name %>
</p>

<p>
  <b>Population:</b>
  <%= @country.population %>
</p>

<p>
  <b>Median age:</b>
  <%= @country.median_age %>
</p>

<p>
  <b>Life expectancy:</b>
  <%= @country.life_expectancy %>
</p>

<p>
  <b>Gross domestic product:</b>
  <%= number_to_currency(@country.gross_domestic_product) %>
</p>

<p>
  <b>Mandatory military service:</b>
  <%= @country.mandatory_military_service %>
</p>


<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CountryData</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="search">
    <% if session[:keyword] %>
      <p>Your last search was for: <%= session[:keyword] %></p>
    <% else %>
      <p>You are searching for the first time.</p>
    <% end %>
    <%= form_tag results_path do %>
      <%= label_tag 'keyword', 'Search' %>
      <%= text_field_tag :keyword %>
      <%= select_tag :my_option, options_for_select([["All Countries", 1], ["Countries with Mandatory military service", 2], ["Countries without Mandatory military service", 3]]) %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
  <ul>
    <li><%= link_to 'Index', world_path %></li>
    <li><%= link_to 'By Population', by_population_path %></li>
    <li><%= link_to 'By Age', by_age_path %></li>
    <li><%= link_to 'By Required Service', by_required_service_path %></li>
  </ul>
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/world/_country.html.erb
<h1><%= country.name %></h1>
<p><b>Population:</b> <%= country.population %></p>
<p><b>Median Age:</b> <%= country.median_age %></p>
<p><b>Life Expectancy:</b> <%= country.life_expectancy %></p>
<p><b>GDP:</b> <%= country.gross_domestic_product %></p>
<p><b>Mandatory Military service:</b> <%= country.mandatory_military_service %></p>

app/views/world/by_age.html.erb
<%= render :partial => 'country', :collection => @countries, :as => 'country'  %>

app/views/world/by_population.html.erb
<%= render :partial => 'country', :collection => @countries, :as => 'country'  %>

app/views/world/by_required_service.html.erb
<% if @countries.empty? %>
  <p>No countries with mandatory military service.</p>
<% end %>
<%= render :partial => 'country', :collection => @countries, :as => 'country'  %>

app/views/world/index.html.erb
<%= render :partial => 'country', :collection => @countries, :as => 'country'  %>

app/views/world/search_results.html.erb
<h1>Search Results for "<%= @keyword %>"</h1>
<% session[:keyword] = @keyword %>
<%= render :partial => 'country', :collection => @countries, :as => 'country'  %>